name: Run pylint

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          # Use locally --disable=R0801,C0301 to better visualize the actual warnings/errors. This will have to be fixed in the future (TODO)
          # R0801: duplicate-code 
          # C0301: Line too long 
          pylint --max-line-length=120 --fail-under=8 --output-format=colorized $(git ls-files '*.py')
      - name: Report Status to Daniel
        if: ${{ always() && github.event.pusher.name == 'danieltheunissen' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_DANIEL_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HDP_WEBHOOK }}
      - name: Report Status to Jonathan
        if: ${{ always() && github.event.pusher.name  == 'JonathanMELIUS' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_JONATHAN_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HDP_WEBHOOK }}
      - name: Report Status to Kristine
        if: ${{ always() && github.event.pusher.name  == 'kristinegusta' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_KRISTINE_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HDP_WEBHOOK }}
      - name: Report Status to Helene
        if: ${{ always() && github.event.pusher.name  == 'hkabbech' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_HELENE_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HDP_WEBHOOK }}
      - name: Report Status general
        if: ${{ always() && github.event.pusher.name != 'danieltheunissen' && github.event.pusher.name != 'JonathanMELIUS' && github.event.pusher.name != 'kristinegusta' && github.event.pusher.name != 'hkabbech' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HDP_WEBHOOK }}
